version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: maestro
      POSTGRES_PASSWORD: maestro123
      POSTGRES_DB: agent_maestro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maestro -d agent_maestro"]
      interval: 5s
      timeout: 5s
      retries: 5

  # wq-maestro:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - redis
  #     - postgres
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - POSTGRES_URL=postgres://maestro:maestro123@postgres:5432/agent_maestro

volumes:
  redis_data:
  postgres_data: