export enum Commands {
  GetStatus = "agent-bridge.getStatus",
  CreateController = "agent-bridge.createController",
  SwitchController = "agent-bridge.switchController",
  SetWorkspacePath = "agent-bridge.setWorkspacePath",
  ShowPanel = "agent-bridge.showPanel",
  SendToRoo = "agent-bridge.sendToRoo",
  ExecuteRooResult = "agent-bridge.executeRooResult",
  StartProcess = "agent-bridge.startProcess",
  ListProcesses = "agent-bridge.listProcesses",
  ShowControllers = "agent-bridge.showControllers",
  SaveRooCodeSettings = "agent-bridge.saveRooCodeSettings",
  RefreshControllers = "agent-bridge.refreshControllers",
  ControllerActions = "agent-bridge.controllerActions",
  ConnectToWSServer = "agent-bridge.connectToWSServer",
  ShutdownContainer = "agent-bridge.shutdownContainer",
}
